In [1]:
import numpy as np

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [32]:
def np_array_from_N_0(n):
    return np.arange(n-1,-1,-1)
     
np_array_from_N_0(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
def fx_array(n):
    import numpy as np
    if type(n)==float:
        n = int(n)
    if not type(n)==int:
        raise Exception('n should be an int or float')
    if n<=0 :
        raise Exception('n should be positive')
  
    arr = np.arange(n-1,-1,-1)
    return np.array(arr)
  
val = fx_array(10)
print(val,type(val))

[9 8 7 6 5 4 3 2 1 0] <class 'numpy.ndarray'>


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [17]:
n = int(input())
np.diag(np.arange(n,-1,-1), k=0)


10


array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [18]:
def np_diag_from_N_0(n):
    return np.sum(np.diag(np.arange(n,-1,-1), k=0))

print(np_diag_from_N_0(10))

55


### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [11]:
from numpy import linalg

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

res = linalg.solve(a, b)
print(f' x = {res[0]}, y = {res[1]}, z = {res[2]}')

 x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555


In [12]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True